"""Generate an OpenAPI 3.0 document for the published gateway surface.

Pure functions only: callers fetch APISIX routes and query templates, then
pass them in. Plugin configurations are never copied into the output — routes
may carry proxy-rewrite headers containing upstream secrets, so only safe,
derived metadata (uri, methods, name, desc, labels, key-auth presence) is
used to build the spec.
"""

from __future__ import annotations

import re
from typing import Any

from app.services.apisix_system_resources import (
    PROTECTED_ROUTE_IDS,
    QUERY_TEMPLATE_WRITE_ROUTE_ID,
)

OPENAPI_VERSION = "3.0.3"
SPEC_TITLE = "UniBridge Gateway API"

# APISIX key-auth reads the API key from the ``apikey`` header by default
# (matches the curl sample generated by ``route_curl`` in the gateway router).
API_KEY_HEADER = "apikey"
SECURITY_SCHEME_NAME = "ApiKeyAuth"

TAG_BUILT_IN = "built-in"
TAG_CUSTOM = "custom"
TAG_QUERY_TEMPLATE = "query-template"

# Public execution prefix for query templates: the ``query-api`` seed route
# proxies ``/api/query/*`` to the service's ``/query/*`` endpoints.
QUERY_TEMPLATE_PUBLIC_PREFIX = "/api/query/templates"

# OpenAPI 3.0 path item operations (APISIX may also list e.g. PURGE).
_ALLOWED_OPERATIONS = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}

# Named bind parameters (``:name``) in template SQL. The negative lookbehind
# skips Postgres-style casts (``::int``) and already-matched binds.
_BIND_PARAM_RE = re.compile(r"(?<![:\w]):([A-Za-z_][A-Za-z0-9_]*)")

_WILDCARD_PARAM = {
    "name": "path",
    "in": "path",
    "required": True,
    "description": "Wildcard path suffix matched by the APISIX route uri.",
    "schema": {"type": "string"},
}


def _security_schemes() -> dict[str, Any]:
    return {
        SECURITY_SCHEME_NAME: {
            "type": "apiKey",
            "in": "header",
            "name": API_KEY_HEADER,
            "description": "UniBridge gateway API key (APISIX key-auth).",
        }
    }


def _route_uris(route: dict[str, Any]) -> list[str]:
    uri = route.get("uri")
    if isinstance(uri, str) and uri:
        return [uri]
    uris = route.get("uris")
    if isinstance(uris, list):
        return [item for item in uris if isinstance(item, str) and item]
    return []


def _openapi_path_for_uri(uri: str) -> tuple[str, bool]:
    """Map an APISIX uri to an OpenAPI path; returns (path, has_wildcard)."""
    if uri.endswith("*"):
        base = uri.rstrip("*").rstrip("/")
        return f"{base}/{{path}}", True
    return uri or "/", False


def _route_methods(route: dict[str, Any]) -> list[str]:
    methods = route.get("methods")
    if not isinstance(methods, list) or not methods:
        methods = ["GET"]
    seen: list[str] = []
    for method in methods:
        if not isinstance(method, str):
            continue
        op = method.lower()
        if op in _ALLOWED_OPERATIONS and op not in seen:
            seen.append(op)
    return seen


def _route_tags(route: dict[str, Any]) -> list[str]:
    tags = [TAG_BUILT_IN if route.get("id") in PROTECTED_ROUTE_IDS else TAG_CUSTOM]
    labels = route.get("labels")
    if isinstance(labels, dict):
        for key in sorted(labels):
            value = labels[key]
            if isinstance(key, str) and isinstance(value, str):
                tags.append(f"{key}:{value}")
    return tags


def _route_requires_key_auth(route: dict[str, Any]) -> bool:
    plugins = route.get("plugins")
    return isinstance(plugins, dict) and "key-auth" in plugins


def _route_operation(route: dict[str, Any], method: str, has_wildcard: bool) -> dict[str, Any]:
    route_id = route.get("id")
    summary = route.get("name") or route_id or "gateway route"
    operation: dict[str, Any] = {
        "summary": str(summary),
        "operationId": f"{method}-{route_id or summary}".replace("/", "-"),
        "tags": _route_tags(route),
        "responses": {"default": {"description": "Response proxied from the upstream service."}},
    }
    desc = route.get("desc")
    if isinstance(desc, str) and desc:
        operation["description"] = desc
    if has_wildcard:
        operation["parameters"] = [dict(_WILDCARD_PARAM)]
    if _route_requires_key_auth(route):
        operation["security"] = [{SECURITY_SCHEME_NAME: []}]
    return operation


def extract_template_params(sql: str) -> list[str]:
    """Extract named bind parameter names (``:name``) from template SQL."""
    seen: list[str] = []
    for name in _BIND_PARAM_RE.findall(sql or ""):
        if name not in seen:
            seen.append(name)
    return seen


def _template_request_body(template: Any) -> dict[str, Any]:
    param_names = extract_template_params(template.sql)
    params_schema: dict[str, Any] = {
        "type": "object",
        "description": "Named bind parameters for the stored query.",
        "properties": {name: {} for name in param_names},
        "additionalProperties": True,
    }
    if param_names:
        params_schema["required"] = param_names
    body_schema: dict[str, Any] = {
        "type": "object",
        "properties": {
            "params": params_schema,
            "limit": {
                "type": "integer",
                "minimum": 1,
                "description": "Override the template default row limit"
                + (f" (default: {template.default_limit})." if template.default_limit else "."),
            },
            "timeout": {
                "type": "integer",
                "minimum": 1,
                "maximum": 300,
                "description": "Override the template default timeout in seconds"
                + (f" (default: {template.timeout})." if template.timeout else "."),
            },
        },
    }
    return {
        "required": bool(param_names),
        "content": {"application/json": {"schema": body_schema}},
    }


def _template_operation(template: Any) -> dict[str, Any]:
    description = template.description or ""
    db_note = f"Runs against database '{template.db_alias}'."
    operation: dict[str, Any] = {
        "summary": template.name,
        "description": f"{description}\n\n{db_note}".strip(),
        "operationId": f"post-query-template-{template.path}".replace("/", "-"),
        "tags": [TAG_QUERY_TEMPLATE],
        "security": [{SECURITY_SCHEME_NAME: []}],
        "requestBody": _template_request_body(template),
        "responses": {
            "200": {
                "description": "Query result rows.",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "columns": {"type": "array", "items": {"type": "string"}},
                                "rows": {"type": "array", "items": {"type": "array", "items": {}}},
                                "row_count": {"type": "integer"},
                                "truncated": {"type": "boolean"},
                                "elapsed_ms": {"type": "integer"},
                            },
                        }
                    }
                },
            }
        },
    }
    return operation


def _template_update_operation(template: Any) -> dict[str, Any]:
    editable_fields = ("sql", "description", "default_limit", "timeout")
    return {
        "summary": f"Edit {template.name}",
        "description": (
            "Edit safe content fields on this existing query template. Requires "
            f"the independently granted `{QUERY_TEMPLATE_WRITE_ROUTE_ID}` route. "
            "Database, path, enabled state, creation, and deletion remain admin-only."
        ),
        "operationId": f"patch-query-template-{template.path}".replace("/", "-"),
        "tags": [TAG_QUERY_TEMPLATE],
        "security": [{SECURITY_SCHEME_NAME: []}],
        "requestBody": {
            "required": True,
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "sql": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Read-only SELECT/EXPLAIN template SQL.",
                            },
                            "description": {"type": "string", "maxLength": 255},
                            "default_limit": {
                                "type": "integer",
                                "minimum": 1,
                                "nullable": True,
                            },
                            "timeout": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 300,
                                "nullable": True,
                            },
                            "expected_updated_at": {
                                "type": "string",
                                "format": "date-time",
                                "description": "Optional optimistic-concurrency value from discovery.",
                            },
                        },
                        "anyOf": [
                            {"required": [field]} for field in editable_fields
                        ],
                    },
                }
            },
        },
        "responses": {
            "200": {"description": "Updated query template."},
            "403": {"description": "Write route, database, or table access is missing."},
            "409": {"description": "The template changed after discovery."},
        },
    }


def build_openapi_spec(
    routes: list[dict[str, Any]],
    templates: list[Any],
    *,
    server_url: str,
    version: str = "unknown",
) -> dict[str, Any]:
    """Build an OpenAPI 3.0 document from APISIX routes and query templates.

    ``templates`` accepts ``QueryTemplate`` ORM rows (or any objects exposing
    ``path``, ``name``, ``description``, ``db_alias``, ``sql``,
    ``default_limit``, ``timeout`` and ``enabled``).
    """
    paths: dict[str, dict[str, Any]] = {}

    for route in routes:
        if not isinstance(route, dict):
            continue
        methods = _route_methods(route)
        for uri in _route_uris(route):
            path, has_wildcard = _openapi_path_for_uri(uri)
            path_item = paths.setdefault(path, {})
            for method in methods:
                if method not in path_item:
                    path_item[method] = _route_operation(route, method, has_wildcard)

    template_write_available = any(
        route.get("id") == QUERY_TEMPLATE_WRITE_ROUTE_ID
        and "patch" in _route_methods(route)
        for route in routes
        if isinstance(route, dict)
    )

    for template in templates:
        if not template.enabled:
            continue
        path = f"{QUERY_TEMPLATE_PUBLIC_PREFIX}/{template.path}"
        path_item = paths.setdefault(path, {})
        path_item["post"] = _template_operation(template)
        if template_write_available:
            path_item["patch"] = _template_update_operation(template)

    return {
        "openapi": OPENAPI_VERSION,
        "info": {
            "title": SPEC_TITLE,
            "version": version,
            "description": (
                "Published API surface of the UniBridge gateway: APISIX routes "
                "(built-in and custom) and enabled query templates."
            ),
        },
        "servers": [
            {
                "url": server_url,
                "description": "UniBridge gateway public base (nginx → APISIX).",
            }
        ],
        "externalDocs": {
            "description": "Query-template discovery, execution, and editing guide.",
            "url": f"{server_url.rstrip('/')}{QUERY_TEMPLATE_PUBLIC_PREFIX}/guide",
        },
        "paths": paths,
        "components": {"securitySchemes": _security_schemes()},
    }
