apisix:
  node_listen: 9080
  enable_admin: true

deployment:
  admin:
    admin_key:
      - name: admin
        key: 40a3a08930ef6bb269cc587f53a0e982
        role: admin
    admin_listen:
      ip: 0.0.0.0
      port: 9180
    allow_admin:
      - 127.0.0.1/32
      - 172.16.0.0/12   # Docker internal networks
  etcd:
    host:
      - "http://etcd:2379"

plugin_attr:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091

plugins:
  - jwt-auth
  - key-auth
  - proxy-rewrite
  - prometheus
  - http-logger
  - error-log-logger
  - ip-restriction
  - limit-req
  - limit-count
  - cors
